### ISSUE TITLE
printCurrentWeather Text Contents

### ISSUE THREAD

**Issue by JackieHodges** [wmccone/UTA-Group8-Project-1#15]
Minor issue. You'll see that when I try to enter in the next city, all the weather condition texts are shown twice.

<img width="983" alt="Screen Shot 2021-02-03 at 12 02 23 PM" src="https://user-images.githubusercontent.com/67762920/106789377-cb898380-6617-11eb-9036-0408bd280606.png">

**Comment by wmccone** [comment]
Just updated the Index file and submitted the fix for this, good catch.
