### ISSUE TITLE
Starting Page HTML

### ISSUE THREAD

**Issue by JackieHodges** [wmccone/UTA-Group8-Project-1#32]
If you were to visit the page for the first time (or clear your local storage and refresh), there are 2 HTML elements I feel like that shouldn't be there at the beginning of the page because you technically don't have a selected city or playlist yet.
<img width="1432" alt="Screen Shot 2021-02-08 at 9 25 48 AM" src="https://user-images.githubusercontent.com/67762920/107240596-b3d34600-69ef-11eb-904b-92026fad70d4.png">

**Comment by JackieHodges** [comment]
just going to remove two lines of html, but add it back in when the city and playlist is entered/fetched.

**Comment by ThatSkiPatroller** [comment]
This has been fixed with the rearrangement of the html elements

**Comment by ThatSkiPatroller** [comment]
This has been fixed with the rearrangement of the html elements
